# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python3_{10..13} )
DISTUTILS_USE_PEP517="setuptools"

inherit distutils-r1 pypi

DESCRIPTION="Library to control webOS based LG TV devices."

HOMEPAGE="https://github.com/chros73/bscpylgtv"
LICENSE=""
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="with-calibration"
RDEPEND=">=dev-python/websockets-8.1[${PYTHON_USEDEP}]
	dev-python/sqlitedict[${PYTHON_USEDEP}]
	with-calibration? ( >=dev-python/numpy-1.17.0[${PYTHON_USEDEP}] )
	${PYTHON_DEPS}"
DEPEND="${RDEPEND}"
REQUIRED_USE="${PYTHON_REQUIRED_USE}"
